# Generated by Django 4.0.3 on 2022-04-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
