# Generated by Django 4.0.3 on 2022-06-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuentas', '0002_aula_curso_profesor_aula_curso_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
