# Generated by Django 4.0.3 on 2022-04-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_delete_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
