# Generated by Django 4.0.3 on 2022-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_orden_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
