# Generated by Django 4.0.3 on 2022-04-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_producto_category_alter_producto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.cliente'),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.producto'),
        ),
    ]
