# Generated by Django 4.0.3 on 2022-06-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_remove_alumno_calificaciones_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_calificaciones',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='cuentas.alumno'),
        ),
    ]
