# Generated by Django 4.0.3 on 2022-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_etiqueta_orden_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(to='cuentas.etiqueta'),
        ),
    ]
