# Generated by Django 4.0.3 on 2022-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_calificaciones_alter_alumno_calificaciones_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_calificaciones',
            name='notas',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Calificaciones',
        ),
    ]
