# Generated by Django 4.0.3 on 2022-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_alter_alumno_calificaciones_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_calificaciones',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='cuentas.alumno'),
        ),
    ]
