# Generated by Django 4.0.3 on 2022-04-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_cliente_usuario_alter_producto_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
    ]
