# Generated by Django 4.0.3 on 2022-06-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_alter_alumno_calificaciones_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno_calificaciones',
            name='curso',
        ),
    ]
