# Generated by Django 4.0.3 on 2022-06-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_remove_alumno_calificaciones_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula_curso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cuentas.curso'),
        ),
    ]
