# Generated by Django 4.0.3 on 2022-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_curso_encurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('1°', '1°'), ('2°', '2°'), ('3°', '3°'), ('4°', '4°'), ('5°', '5°')], max_length=200, null=True)),
                ('año', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=200, null=True)),
                ('seccion', models.CharField(max_length=10, null=True)),
                ('salon', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
