# Generated by Django 4.0.3 on 2022-06-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_alter_aula_curso_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno_calificaciones',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.curso'),
        ),
    ]
