# Generated by Django 4.0.3 on 2022-05-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_aulas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
    ]
