# Generated by Django 4.0.3 on 2022-06-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_alumno_calificaciones_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_calificaciones',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.aula_curso'),
        ),
    ]
