# Generated by Django 4.0.3 on 2022-05-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0017_rename_aulas_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='encurso',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.aula'),
        ),
    ]
