# Generated by Django 4.0.3 on 2022-05-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0018_encurso_aula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnCurso',
            new_name='Cursando',
        ),
    ]
