# Generated by Django 4.0.3 on 2022-06-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0020_alter_alumno_apellido_m_alter_alumno_apellido_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno_calificaciones',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cuentas.curso'),
        ),
    ]
