# Generated by Django 4.0.3 on 2022-06-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0021_alter_alumno_calificaciones_curso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumno_calificaciones',
            unique_together=set(),
        ),
    ]
